POST  http://192.168.2.108:18082/cron/ HTTP/1.1
Content-Type:  application/json

{
    "cron_id": "post_test_cron222",
    "cron_type": "post",
    "cron_body": "gedatasfasdfasdfat",
    "cron_time_trigger": "cron",
    "cron_time_body": {"second": "10", "minute": "*/3"}
}
